version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:80
      - REDIS_HOST=redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
